module.exports = {
	name: 'TWFND',
	execute(message) {
		message.channel.send('A distant humming filled the empty streets of the old, abandoned city, singing an old tune from hundreds of years before. The deep footsteps in thick, heavy snow made a soft thud that echoed across the otherwise silent, lifeless streets, rebounding from window to window. A bright light came from the hand of the man who made these noises, coming from an old, rusty flashlight, tightly strapped to his revolver, which made a small path through the seemingly infinite black ink of darkness, lighting up whatever lied in front of it. The man was hardly visible in the overcasting shadow of night; the only noticeable features being his tall, muscular build, and his menacing cape, which dangled down to the ground, sliding slowly across the snow, alongside a large, dark hood, that hid anything   that could have been seen on his face, even in the darkness. He looked like an adventurer, an explorer, someone who was searching for some unknown treasure he desired, but it was very clear that, if one could see the mans face under his secretive hood and the shroud of darkness, he had a destination in mind. He didn’t have the look of a mercenary, though he wore similar clothing. The look in his eyes proved otherwise: he was set on something, a goal, a mission, a destiny, and to him, there was no wall he couldn’t climb that would stop him from reaching that destiny.');
	  	message.channel.send('He walked into an old subway station, the walls rusted by time, yellowed and dusty, falling apart and peeling. One of the walls had crumbled down, leaving nothing but the metal supports and the frame behind it, of which had rusted, some of it collapsed. The station was fragile, it had seen countless years and countless battles. There was a massive door blocking his entry to the station, it’s metal somewhat clean and well kept, unlike the rest of the station, and it was tied together by a mix of bolts, screws, and tape. On the middle there was a large insignia: a red rectangle with three white swords; the flag of the Republic. It appeared crude, but it served it’s purpose. He put his gun quickly into his holster, turning off its flashlight, then raised his hand and pounded it on the door.');
    		message.channel.send('The door began to creak, dust and frosted snow coming out of it as the gate opened. The lights inside were almost blinding compared to the darkness that remained outside the station, and the shadow of a man, clearly a guard of the station, was cast down on the adventurer, openly pointing his double-barrel shotgun at him.');
    		message.channel.send('"What are you doin’ here, old man?" the guard said in a very serious manner, speaking in a voice so deep it almost seemed fake, almost as though he was trying to assert dominance over the adventurer.');
    		message.channel.send('"I am on official business with the Aeternum Republic, here to see Doctor Cassius Devitt," the man replied swiftly and sharply.');
    		message.channel.send('"The Plague Doctor? What for? Who sent you?" the guard responded with anger, believing the adventurer was nothing more than a fake and a liar. He responded with nothing, instead pulling a small piece of paper out of his pocket, gesturing it towards the guard. He took it fiercely with one hand, keeping the other on the shotgun pointed at the man, acting as though he were about to rip the sheet in half. The guard stared at the paper for a moment, then looked up from the paper directly at the adventurer, then back down at the paper. He growled angrily, clearly showing his teeth, and frowned at the man.');
    		message.channel.send('“Authority to see the Doctor from the Executor himself… fine. Come with me,” the guard handed the adventurer back his paper, who then proceeded to put it back into his pocket. The guard held his shotgun at his side and began to walk the man through the station.');
    		message.channel.send('“You’re the first man to come see him in a while. He might not be so… sociable,” the guard explained to him, looking forward, keeping his eyes off the adventurer out of hatred, possibly even out of fear.');
    		message.channel.send('“I’ve dealt with worse.”');
    		message.channel.send('“If you don’t mind me asking, what business do are you here to see him about?”');
    		message.channel.send('“I do mind you asking.”');
    		message.channel.send('People were somewhat scarce at the station, most appeared to only be passing through, coming onto the platform itself to make their way into the tunnel on the opposite side, or to trade with one of the very few salesmen who made a living off of the trade there. There was one of these that caught the adventurer’s eye for a moment: a man standing behind one of these market stands, middle aged and in a bad state of health, with a large scar coming down from the top of his forehead all the way to the top of his lip, completely covering one eye and rendering it useless. Two guards appeared in front of his stand suddenly, both with large guns drawn. They began screaming at the old man, but the old man almost completely ignored them.');
    		message.channel.send('“…if you don’t pay up right now… we have orders on the behalf of the Republic to seize tax…” the guards shouted at him. Much to their surprise, the old man came back with just the same force, but his was not shown in words. Instead, he reached under his cabinet for something. The guards most likely thought it was the money he had to pay, but the old man would much rather die than let the guards take from him again.');
    		message.channel.send('Like a quick flash of light, he whipped out a pistol and killed one of the guards in front of him, square in between the eyes. A good shot for a man his age. He took the gun and pointed it at the other and pulled the trigger. An empty click. The remaining guard simply laughed at the old man, and raised his gun at him. The adventurer turned away quickly, as in spite of all the things he had seen, he still couldn’t stand to see a poor old man suffer such a fate as this. The gunshot thundered across the station, echoing across it’s aging halls and into the tunnels.');
    		message.channel.send('The adventurer clenched his fist in anger, wishing he could reach for his pistol and do just as the old man had done, but he knew that there was no way he would be able to get out alive if he did something as stupid as that. Then again, he was about to meet Cassius face to face, for the first time in years, how would he survive something like that? The man could only vaguely remember his first time meeting the doctor, thinking only of the menacing plague doctor helmet that he had so ingeniously made into a respirator.');
    
  },
};
