module.exports = {
	name: 'twfnd',
	execute(message) {
		message.channel.send('A distant humming filled the empty streets of the old, abandoned city, singing an old tune from hundreds of years before. The deep footsteps in thick, heavy snow made a soft thud that echoed across the otherwise silent, lifeless streets, rebounding from window to window. A bright light came from the hand of the man who made these noises, coming from an old, rusty flashlight, tightly strapped to his revolver, which made a small path through the seemingly infinite black ink of darkness, lighting up whatever lied in front of it. The man was hardly visible in the overcasting shadow of night; the only noticeable features being his tall, muscular build, and his menacing cape, which dangled down to the ground, sliding slowly across the snow, alongside a large, dark hood, that hid anything   that could have been seen on his face, even in the darkness. He looked like an adventurer, an explorer, someone who was searching for some unknown treasure he desired, but it was very clear that, if one could see the mans face under his secretive hood and the shroud of darkness, he had a destination in mind. He didn’t have the look of a mercenary, though he wore similar clothing. The look in his eyes proved otherwise: he was set on something, a goal, a mission, a destiny, and to him, there was no wall he couldn’t climb that would stop him from reaching that destiny.');
	  	message.channel.send('He walked into an old subway station, the walls rusted by time, yellowed and dusty, falling apart and peeling. One of the walls had crumbled down, leaving nothing but the metal supports and the frame behind it, of which had rusted, some of it collapsed. The station was fragile, it had seen countless years and countless battles. There was a massive door blocking his entry to the station, it’s metal somewhat clean and well kept, unlike the rest of the station, and it was tied together by a mix of bolts, screws, and tape. On the middle there was a large insignia: a red rectangle with three white swords; the flag of the Republic. It appeared crude, but it served it’s purpose. He put his gun quickly into his holster, turning off its flashlight, then raised his hand and pounded it on the door.');
    		message.channel.send('The door began to creak, dust and frosted snow coming out of it as the gate opened. The lights inside were almost blinding compared to the darkness that remained outside the station, and the shadow of a man, clearly a guard of the station, was cast down on the adventurer, openly pointing his double-barrel shotgun at him.');
    		message.channel.send('"What are you doin’ here, old man?" the guard said in a very serious manner, speaking in a voice so deep it almost seemed fake, almost as though he was trying to assert dominance over the adventurer.');
    		message.channel.send('"I am on official business with the Aeternum Republic, here to see Doctor Cassius Devitt," the man replied swiftly and sharply.');
    		message.channel.send('"The Plague Doctor? What for? Who sent you?" the guard responded with anger, believing the adventurer was nothing more than a fake and a liar. He responded with nothing, instead pulling a small piece of paper out of his pocket, gesturing it towards the guard. He took it fiercely with one hand, keeping the other on the shotgun pointed at the man, acting as though he were about to rip the sheet in half. The guard stared at the paper for a moment, then looked up from the paper directly at the adventurer, then back down at the paper. He growled angrily, clearly showing his teeth, and frowned at the man.');
    		message.channel.send('“Authority to see the Doctor from the Executor himself… fine. Come with me,” the guard handed the adventurer back his paper, who then proceeded to put it back into his pocket. The guard held his shotgun at his side and began to walk the man through the station.');
    		message.channel.send('“You’re the first man to come see him in a while. He might not be so… sociable,” the guard explained to him, looking forward, keeping his eyes off the adventurer out of hatred, possibly even out of fear.');
    		message.channel.send('“I’ve dealt with worse.”');
    		message.channel.send('“If you don’t mind me asking, what business do are you here to see him about?”');
    		message.channel.send('“I do mind you asking.”');
    		message.channel.send('People were somewhat scarce at the station, most appeared to only be passing through, coming onto the platform itself to make their way into the tunnel on the opposite side, or to trade with one of the very few salesmen who made a living off of the trade there. There was one of these that caught the adventurer’s eye for a moment: a man standing behind one of these market stands, middle aged and in a bad state of health, with a large scar coming down from the top of his forehead all the way to the top of his lip, completely covering one eye and rendering it useless. Two guards appeared in front of his stand suddenly, both with large guns drawn. They began screaming at the old man, but the old man almost completely ignored them.');
    		message.channel.send('“…if you don’t pay up right now… we have orders on the behalf of the Republic to seize tax…” the guards shouted at him. Much to their surprise, the old man came back with just the same force, but his was not shown in words. Instead, he reached under his cabinet for something. The guards most likely thought it was the money he had to pay, but the old man would much rather die than let the guards take from him again.');
    		message.channel.send('Like a quick flash of light, he whipped out a pistol and killed one of the guards in front of him, square in between the eyes. A good shot for a man his age. He took the gun and pointed it at the other and pulled the trigger. An empty click. The remaining guard simply laughed at the old man, and raised his gun at him. The adventurer turned away quickly, as in spite of all the things he had seen, he still couldn’t stand to see a poor old man suffer such a fate as this. The gunshot thundered across the station, echoing across it’s aging halls and into the tunnels.');
    		message.channel.send('The adventurer clenched his fist in anger, wishing he could reach for his pistol and do just as the old man had done, but he knew that there was no way he would be able to get out alive if he did something as stupid as that. Then again, he was about to meet Cassius face to face, for the first time in years, how would he survive something like that? The man could only vaguely remember his first time meeting the doctor, thinking only of the menacing plague doctor helmet that he had so ingeniously made into a respirator.');
		message.channel.send('How many years ago had that been? Three? It had been fourteen years since he had fled the Constanti Academy, but he didn’t count that as meeting him. Both the adventurer himself and the crazed doctor had changed too much for events that long ago to matter anymore. Had it been three years? Only three? It had felt like an eternity, but to him time had become beyond comprehension. It was hard to keep track of time during the war, and events sped past him, running away into the deep pits of his mind, hiding behind old, fragmented memories, torn apart by time. Whenever the adventurer tried to think too hard, to remember what Cassius looked like or sounded like, the memory completely vanished, the only thing left behind being his sinister laugh, made metallic by the thick gas he wore. ');
		message.channel.send('He rolled up the sleeve of his coat briefly on his right arm and looked at his wrist. The numbers still remained: 7935, and though the burned mark had been heavily decayed with time, it was still easily readable. The numbers didn’t mean that he was the 7935th to go through with the procedure, only that he was the 7935th one to go into the doctor’s “care”. Care meant almost anything to Cassius, from replacing a limb with a robotic one, to disassembling someone simply to study them; to see how they worked.');
		message.channel.send('How did he even manage to escape that hellish place? The adventurer shook his head quickly, as to force the ideas out of his mind. The pains he withheld during those five hours were the worst of his life, and the tears that were ripped open healed only to scars, of which could never be truly fixed. Five hours of hell left a mark on his mind that endless years of peace would never be able restore. It wasn’t like that mattered, though: peace would never come for him, and he knew that and had accepted it long ago.');
		message.channel.send('The adventurer and his escort arrived at the end of the hall, at a large, rusted metal door, with no windows or possible ways of seeing out. Two white robed guards with black masks stood at each side of the door, each holding a similarly painted shotgun, aimed towards the ground, held in both hands. They looked much more formal and professional than the scrapped-armor covered soldiers that roamed the streets. The guards raised their guns silently towards the adventurer and his escort.');
		message.channel.send('“At ease!” his escort put his hand up, signaling the guards to lower their weapons, though they did not, “He’s here to see Cassius, he has orders, from the Executor.” He gestured for the adventurer to give them the sheet of paper he held, and he did so. The left hand guard walked up and snatched it out of his hand, staring at it with eyes that couldn’t be seen behind the immense, black mask. The guard nodded, putting the paper in his pocket, and opened the door, letting the adventurer through without a word.');
		message.channel.send('The room that stood before him was black and empty, even darker than the night that awaited him outside the station. Soon, the bright light from behind him began to dissipate: someone had closed the door. The door gave a loud thud as it finally shut, trapping the adventurer inside with the doctor. The adventurer removed his hood and took out his revolver.');
		message.channel.send('“Cassius, old friend, it has been a while hasn’t it?” he said, looking around the room, hoping to see something out of the darkness. A deep, heavy, metallic breathing began to come from what appeared to be the back of the room. A small light appeared behind the place where the breathing was coming from, illuminating a tall, menacing figure. A deep and heavy laugh followed, a laugh that had haunted the dreams- well, nightmares- of the adventurer for years.');
		message.channel.send('“Adrian Bauer? Your courage inspires me, yet your idiocracy makes me cringe,” the doctor said, at last revealing his metallic voice to the adventurer, “You could have been quite a fine soldier, you know? All I needed to do was make a handful of… adjustments.”');
		message.channel.send('“Torture and partial brain removal? You’re a sociopath,” Adrian spoke calmly, yet his shaking arms and sweating palms said otherwise. Cassius simply sighed, letting loose an almost robotic exhale.');
		message.channel.send('“The shadow of what could have been haunts over me still, you know. I’ve tried to forget the name, truthfully. Adrian Bauer. He died as he left the Constanti Academy. All you could have been, gone and dead. Quite a shame.”');
		message.channel.send('“I don’t regret any of it.”');
		message.channel.send('“Really? Not even after what happened to Anna?”');
		message.channel.send('“If I hadn’t left, you would have made me murder her with my own hands,” Adrian clenched his fist tighter, the bringing up of his mother, especially her death, brought upon him nothing but hatred for the man he spoke with.');
		message.channel.send('“Perhaps, but a good, loyal soldier would be willing to do such a thing. And I assure you, I could have made you loyal. Perhaps I still can?” the Doctor said, laughing again as he tapped a button he held in his hand, and a set of bright lights turned on, one in each corner of the hellish laboratory. However, the adventurer wished the lights could remain off: the sights would be enough to haunt him for the rest of his days.');
		message.channel.send('The walls were plain white, in somewhat good condition,aside from the immense stains of blood. Scratch marks from desperate “patients” drained of all hope, with nothing more than the wish to escape, but well knowing that that wish would never come true. The more the adventurer looked around the room, the more he realized that the blood had almost left no surface untouched. In the middle of the room stood an operating table, with a man, presumably dead, lying with his back up on it. The patient wore pants and shoes, but he did not have his shirt on, instead his back was laid open, with a massive scar climbing across it, cutting in so deep that it revealed his spine. There were numerous wires and cables connected to the spine, as well as metal braces that connected the spine to these wires. The man’s head was shaved bald, with the left half of his head cut open, revealing his brain, with another large brace connecting the patient’s mind to another set of wires. All the wires, both from the spine and the brain, connected to a small battery, no larger than a man’s hand and no heavier than maybe a dozen pounds, which was attached to the patient’s leg. A small piece of a cloth tarp covered the right arm of the poor man, and numerous wires from the battery, spine, and brain went under the tarp to his hand.');
		message.channel.send('The adventurer couldn’t take his eyes off the patient, not because of awe, but because of dread and a deep feeling of utter hopelessness. Despite this, he tightened his grip on his revolver and prepared to shoot. The Doctor stood behind the table where he worked on his cyborg menace, and he was just as the adventurer remembered him: a tall figure, wearing a pitch black set of bulletproof armor and blood stained, white doctor gloves, and his face was completely hidden by a spotlessly white plague doctor’s mask, with a number of tubes coming out of it, onto a small respirator near his chest, which was, like the rest of the doctor, coated in armor. His armor and clothes were stained dark red with the blood of his patients.');
		message.channel.send('“Beautiful isn’t it?” the madman let loose his metallic laugh once more, then looked at the, “I do apologize for the… mess. Had I known you were coming, Mr. Bauer, I would have prepared myself accordingly.” The Doctor glanced briefly at the adventurer’s pistol, then back up at the grim, horrified look on his face. The adventurer was scowling angrily, looking like he was about to tear someone in half, his fists were clenched, one around his revolver, the other around nothing but misty air, yet still he did not shoot the doctor.');
		message.channel.send('“Do not worry, Mr. Brauer, he came willingly. We promised him immortality, a life without fear and pain, in return for only a lifetime of service to the Republic! It sounds like a wonderful offer,” the doctor’s voice was bright and happy, yet still menacing, but it suddenly deepened as he told the man, “We didn’t lie to him, really. We just… didn’t tell him some of the lesser things that might occur after the surgery.”');
		message.channel.send('Adrian watched the doctor closely as he walked towards a wall with a very large scratch mark and ran his hand along it, “Once he heard about the true process of the surgery- transformation I should call it, really. A normal surgery works to fix something, change something. My surgery, my… transformation… works to make one perfect. But I’m getting off track,” Cassius laughed lightly as he continues his story, “Once he had heard about the real process of the transformation, he did his very best in an attempt to escape. We slaughtered his attempt, but,” the Doctor traced his hand across the large scar on the wall once more, “his attempt did come at a cost to us, and to him. His personality was broken, he could never be truly fixed. He could never be the same as he was before the transformation, and I made sure of that. Besides the normal removal of the amygdala, I also removed and damaged a large section, of the frontal lobe- specifically to destroy his personality. He acts like an ape, almost, yet more sophisticated, almost like a mercenary. But you know what I didn’t remove? Hatred. And all I need to do in order to turn enable this hatred,” the Doctor reached into his pocket and pulled out a small device, and flicked a button on it, “is press a button.”');
		message.channel.send('The adventurer backed away from the Doctor and his patient. The patient began to rise slowly, first putting his hand, the one not covered by cloth, onto the bed and pushing himself up. He took his right leg and raised it to stand, then got up into the other, leaving himself to crouch with one hand on the table. He stood up fully, with his back to the adventurer, but slowly turned to face him and jump off the table, standing right in front of him and stared him in the eyes. The eyes of the patient were unblinking, nor did they ever disconnect themselves from the eyes of the adventurer.');
		message.channel.send('“What is this? What have you-”');
		message.channel.send('“A patient, Mr. Bauer. One of my proudest creations, only below Cassia.”');
		message.channel.send('**‘This isn’t a creation, it’s a monstrosity!”**');
		message.channel.send('“A monstrosity, please! Mr. Bauer, I taught you to be a gentlemen, now show the respect you’ve learned!” the Doctor said, laughing as he looked over to Adrian, who simply glared silently, the same look of hatred on his face.');
		message.channel.send('“Now, I am dearly sorry, Mr. Bauer, but I am afraid I won’t be able to let you leave this place. If the Rebellion got word of this, why, the Executor would give me hell!” he laughed again, likely giving some menacing grin from before. Adrian raised his arm to shoot his pistol, but before he could shoot, the patient grabbed him by the neck with his completely robotic left hand, choking and holding him above the ground, his fist like a clamp. In a last attempt for life, he shot his pistol, rapidly and randomly. Six loud bangs, all of which echoed throughout the halls, each of them missing the creation and it’s maker. The adventurer gagged for a breath, hoping to keep consciousness, but to no avail. He felt his head getting heavy, and felt himself collapse as the robotic hand finally let him go. Yet even after he was able to breath, his vision still faded to black.');
		message.channel.send('“Put him with the others,” he could hear the Plague Doctor say as he finally failed himself, and let himself into the darkness of unconsciousness.');
    
  },
};
