module.exports = {
	name: 'entius',
	description: 'link to ventius',
	execute(message, args) {
   		message.channel.send('**Map and Brief Introduction to the Ventius Sector** \n https://cdn.discordapp.com/attachments/825416086920626236/825416387143925820/Intro_Screen.png');
   		message.channel.send('**SPECIES GENERAL INFO** \nGeneral information about the specific species of the Ventius Sector. \nNot in any particular order.\n  \n*Ventius Sector Species: General Overview*, a list and brief description of each species from the Ventius Sector. 6 pages, 1856 words. \n<https://docs.google.com/document/d/1IHoKlXv7TCUdLbw1KGN9Yp4KkKWvSHS8VrkR1WJwpok/edit#>\n*Ventius Sector Species: The Sehan*, an in-depth view of the history, anatomy, and sociology of the Sehan. 8 pages, 4207 words.\n<https://docs.google.com/document/d/1ZnQAMiMhx_TN9A-vHOGKZEH2K1peps4IcEshaRJHcbI/edit>\n*Ventius Sector Species: The Monolites*, an in-depth view of the history, anatomy, and sociology of the Monolites. 12 pages, 6501 words.\n<https://docs.google.com/document/d/17wwCEiv1SJZVgHpY6w8_NJYnVkNl4pD1EPQg5WjcybY/edit>\n*Ventius Sector Species: The Katorians*, an in-depth view of the history, anatomy, and sociology of the Katorians. 12 pages, 6714 words.\n<https://docs.google.com/document/d/1PJGnvJZXZCUKuKsd7QR9mgRfumvslndubwOoQa53t2I/edit>\n*Ventius Sector Species: The Kavri*, an in-depth view of the history, anatomy, and sociology of the Kavri. 14 pages, 8390 words.\n<https://docs.google.com/document/d/1dv9Ke8aASC9S2NAGZ_nrza2tFB1MlCD06POUlTc2zL8/edit>\n*Ventius Sector Species: The Sotran*, an in-depth view of the history, anatomy, and sociology of the Sotran. 5 pages, 2875 words.\n<https://docs.google.com/document/d/1af7SPT8SOmEu4USPyeWcgHH065T47X1lAUq8wtCFp0Q/edit> \n*Ventius Sector Species: The Kyrites*, an in-depth view of the history, anatomy, and sociology of the Kyrites. 5 pages, 2599 words.\n<https://docs.google.com/document/d/1p_jLSSoyp9OCslQ8MRmCvMe74pLxmkP3A3oalIBtVIs/edit>');
  		message.channel.send('**FACTIONS GENERAL INFO**General information about the specific factions of the Ventius Sector.\n Not in any particular order.\n \n *Interstellar Socialist Union General Info*, a document detailing the history, culture, technology, and other details of the ISU. 18 pages, 8392 words.\n <https://docs.google.com/document/d/1sOPeeIHnb0zAjNavnqK1HUusUqT_XFO5pvYq3kVis4I/edit>\n *Eclipsian Kingdom General Info*, a document detailing the history, culture, technology, and other details of the Eclipsians. 8 pages, 3556 words.\n <https://docs.google.com/document/d/1gRGG0MJ4PH_mwlrEwFsPbjDn7Lvnp5rPkqK704HaTxY/edit#>\n *Legio Astrae Republicae General Info*, a document detailing the history, culture, technology, and other details of the Legion. 15 pages, 7214 words.\n <https://docs.google.com/document/d/1RWhk7ikYGP0weuaDsS_dpdhdOqZGyvqUMRWvnnrqLfI/edit>\n *Athens Tech Corporation General Info*, a document detailing the history, culture, technology, and other details of the ATC. 7 pages, 2874 words.\n <https://docs.google.com/document/d/16VNRIYTphcIKSKJFjvT-yox2wY4lXkkexA2JJq_tZk0/edit#>');
		message.channel.send('**STANDARD LENGTH SHORT STORIES**\nGenerally range from 3-10 pages, though most are about 4-5. A quick read, but a little bit more of a time sink than the one-page shorts.\nOrdered from *newest* to *oldest*.\n\n*Militia’s Penance*, a story about the evacuation after Revalia’s fall. 3 pages, 1349 words.\n<https://docs.google.com/document/d/1wa-Lp5v2xeP8FDvomR9BGEvBHHA3vDA_lwWWAZqVa4A/edit>\n*Breathless Silence*, a story about a crewman on a backwater battleship fighting for his life during an attack. 4 pages, 1940 words.\n<https://docs.google.com/document/d/1N7H99ksoHlnWVxCQWnXUf_JlvnQu3OCn460uE3vNnjQ/edit>\n*Left to Drift*, a story about a silent base at the edge of the sector and the team sent to investigate it. 6 pages, 2424 words.\n<https://docs.google.com/document/d/1O1bN6ksHVnz9t6YR3kolCnGZ-v7cDK3YKnkOIh1lAp8/edit>\n*Shattered Luck*, a story about a boy trying to survive the invasion of his hometown. 4 pages, 2057 words.\n<https://docs.google.com/document/d/1VldGTpaZ19ELKpVYc3z_tChoeOI839G2UUkFGKww_SE/edit>\n*One to None*, a story of group of Guardsmen scouting out a long-lost battle station. 14 pages, 7982 words.\n<https://docs.google.com/document/d/1G24AzQm-HqcvAfxrvJ3nJaOVp9TRRcWdrnBqZ2AtXyQ/edit#heading=h.47esg4sackk5>\n*Tertiary Sunset*, a story about a sole survivor Marine hunting for an enemy commander in an Eclipsian city. 6 pages, 3823 words.\n<https://docs.google.com/document/d/1NES6UfxXo1vNe7E8BEStZI6OZvqExg-KniyI8HlUNfA/edit>\n*Sudden Chill*, a story about an untrained Space Trooper trying to get through the wreckage of a new war. 5 pages, 2311 words.\n<https://docs.google.com/document/d/1hy8bkvAoWMWPbqt1-ylRZhfYTV_GE5PTVdKXwuD9XLs/edit#>\n*Operation: Black Bale*, a story of a guardsman fireteam hunting a terrorist group in the farmlands of a distant world. 5 pages, 2514 words.\n<https://docs.google.com/document/d/1_LLXiT6-pA6V5VbudUoJ4Cd9Ym-0iwZrdNXsZClPFV4/edit#>');
	
	
	
	
	
	
	
	
	
	}
}
